Update mirrorNode.yml
"curl" with -w "%{http_code}" 
command captures both response body and HTTP status code. Response is saved to a response.json file and HTTP status code is stored in RESPONSE.

diff --git a/.github/workflows/mirrorNode.yml b/.github/workflows/mirrorNode.yml
--- a/.github/workflows/mirrorNode.yml
+++ b/.github/workflows/mirrorNode.yml
@@ -21,4 +21,14 @@ jobs:
           echo "Account ID: ${{ steps.solo.outputs.accountId }}"
           echo "Private Key: ${{ steps.solo.outputs.privateKey }}"
           echo "Public Key: ${{ steps.solo.outputs.publicKey }}"
-          curl -X 'GET' 'http://localhost:8080/api/v1/network/nodes' -H 'accept: application/json'
+          RESPONSE=$(curl -s -w "%{http_code}" -X 'GET' 'http://localhost:8080/api/v1/network/nodes' -H 'accept: application/json' -o response.json)
+
+        
+          if [ "$RESPONSE" -ne 200 ]; then
+            echo "Error: API request failed with status code $RESPONSE"
+            cat response.json
+            exit 1
+          else
+            echo "API request successful"
+            cat response.json
+          fi
